- .yarn/versions/2a4c46d5.yml
- README.md
- src/hooks/useIsNodeSelected.ts
- src/index.ts
Adds a convenience hook for the most common use case of `useSelectNode`, which is just getting a boolean value describing whether the node is currently selected or not (to use for conditionally setting a class name, for example).
> Add a useIsNodeSelected hook

- .yarn/versions/1cfdbe48.yml
- src/components/CustomNodeView.tsx
- src/components/NodeView.tsx
- src/components/ReactNodeView.tsx
Plain custom node views had been broken since we implemented SSR. When they were pulled into their own component, it messed up some of the layout effect ordering and triggering, such that we no longer attached them to the DOM.
To resolve this, the NodeView component now either renders ReactNodeView or CustomNodeView, each of which manages its own full lifecycle, decorations, etc.
> Fully split CustomNodeView into a separate, memoized component

- .yarn/versions/4dc8fc98.yml
- src/components/OutputSpec.tsx
- src/plugins/componentEventListeners.ts
- src/plugins/reactKeys.ts
- vite.config.ts
- yarn.lock
Also fixes some instances of @nytimes/react-prosemirror to @handlewithcare/react-prosemirror
> Configure vite to target esnext

- .yarn/versions/e1488bb0.yml
- src/hooks/__tests__/useEditorViewLayoutEffect.test.tsx
- src/hooks/useEditorEffect.ts
- yarn.lock
Fixes nytimes/react-prosemirror#101, #8 
During Suspense, it's possible for the layout effect cleanup function that calls `view.destroy()` to be run immediately before the layout group effect that executes `useEditorEffect` callbacks. This results in calling those callbacks with a destroyed editor (one without a docView), which crashes the editor. This can be simulated in Strict Mode with the sample code from #8.
To fix this, we avoid calling useEditorEffect callbacks if the view that we have access to is destroyed. The next render will produce a new, undestroyed EditorView and trigger another callback call, so this doesn't result in any missed calls!
> Prevent running editor effects with a destroyed view during strict mode and suspense

- .eslintrc.json
- .yarn/versions/995d0251.yml
- src/components/CustomNodeView.tsx
- src/components/LayoutGroup.tsx
- src/components/MarkView.tsx
- src/components/NativeWidgetView.tsx
- src/components/SeparatorHackView.tsx
- src/components/TrailingHackView.tsx
- src/components/WidgetView.tsx
- src/hooks/useClientLayoutEffect.ts
- src/hooks/useEditor.ts
- src/hooks/useLayoutGroupEffect.ts
- src/hooks/useNodeViewDescriptor.ts
This is essentially `useIsomorphicLayoutEffect`. It's unclear to me why that library uses a useEffect on the server, since useEffects _also_ do not run on the server.
> Add useClientLayoutEffect to quiet warnings during SSR

- .yarn/versions/492befb0.yml
- src/components/MarkView.tsx
- src/components/OutputSpec.tsx
- src/components/__tests__/ProseMirror.draw.test.tsx
ProseMirror doesn't actually require holes in mark output specs!
> https://prosemirror.net/docs/ref/#model.MarkSpec.toDOM
>
> When the resulting spec contains a hole, that is where the marked content is placed. Otherwise, it is appended to the top node.
This updates the OutputSpec component so that it automatically inserts the hole for marks at the top level, matching the prosemirror-view implementation
> Hole free marks

- .yarn/versions/09801a45.yml
- demo/schema.ts
- package.json
- src/props.ts
- yarn.lock
Previously, we used the browser's built in CSSStyleSheet
to parse CSS and transform it into React-compatible style
props. This is unavailable in SSR contexts, so we switch
to a pure-JavaScript library, css-tree, which supports
parsing CSS in the browser and on the server.
> Switch to css-tree for parsing CSS 

- .yarn/versions/e4bd3158.yml
- README.md
- src/components/CustomNodeView.tsx
- src/components/ReactNodeView.tsx
- src/contexts/IgnoreMutationContext.ts
- src/hooks/useClientOnly.ts
- src/hooks/useEditor.ts
- src/hooks/useEditorEventCallback.ts
- src/hooks/useIgnoreMutation.ts
- src/hooks/useNodeViewDescriptor.ts
- src/index.ts
- src/viewdesc.ts
Passes through stopEvent, ignoreMutation, and selectNode hooks
to the NodeViewDesc for non-React custom node views.
Also adds a `useIgnoreMutation` React hook for React-based
custom node views to specify a custom ignoreMutation hook.
Also also, fixes the useClientOnly implementation (now uses `useSyncExternalStore` to avoid unnecessary double renders on the client with newly mounted components) and issues with Strict/Concurrent mode for custom node views.
> Custom node view improvements

- .yarn/versions/e610ba97.yml
- README.md
- demo/nodeViews/CodeBlock.tsx
- src/components/NodeViewComponentProps.tsx
- src/components/ProseMirror.tsx
- src/components/ReactNodeView.tsx
- src/components/__tests__/ProseMirror.draw-decoration.test.tsx
- src/components/__tests__/ProseMirror.draw.test.tsx
- src/components/__tests__/ProseMirror.node-view.test.tsx
- src/components/__tests__/ProseMirror.test.tsx
- src/contexts/NodeViewContext.tsx
Hi,
In React 19, [ref is a regular props](https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop) which mean that the type of `nodeViews` is a bit too strict when using react 19.
This PR update the type to use `ComponentType` instead of `ForwardRefExoticComponent`.
> Use ComponentType for nodeViews prop type (fro React 19)

- .yarn/versions/22ef9f0f.yml
- package.json
- src/props.ts
- yarn.lock
Fixes #38.
It turns out, it's possible to directly pass style strings to the underlying DOM nodes by just... capitalizing the prop name? Quite goofy, but it allows us to entirely drop any CSS parsing functionality, which is great.
> Drop css-tree package. Pass styles to DOM directly

- .yarn/versions/1a93b4cd.yml
- demo/schema.ts
- src/components/OutputSpec.tsx
Fixes #44. When we added support for marks with unspecified holes, we unintentionally added a bug where we rendered the entire markup for the mark nested within the initial markup. We just want to render the children in the hole!
> Don't double-nest marks with unspecified holes

- .yarn/versions/4206cfbe.yml
- src/props.ts
React 19 dropped the "Warning:" prefix from its warning about casing the `style` prop incorrectly
> Quiet React DOM STYLE prop warning in React 19

- .yarn/versions/a2296abd.yml
- src/components/CustomNodeView.tsx
The previous "fix" here unintentionally relied on StrictMode in order to operate correctly. In a non-strict/non-concurrent render, where effect destructors are not called unless their dependencies change, we were never actually appending the dom of the custom node view to the root.
I've confirmed that this now works correctly for _both_ strict and non-strict modes!
> Fix custom node views when strict mode is _off_

- .yarn/versions/7c54e89e.yml
- README.md
- package.json
- yarn.lock
Bump max React version to 19.1. Also moves react-reconciler to peer dependencies and adds some guidance on how to install the correct version of it for your react version.
> React 19.1

- .yarn/versions/7fcd8d83.yml
- src/components/ChildNodeViews.tsx
When we memoized the ChildNodeViews component, we started relying on offset to sort child views. This caused instability in the ordering when widgets are rendered at the start position of a node (because then the node and the widget had the same offset). `iterDeco` already orders these correctly, so now we just track the order that these come out of `iterDeco` and use that to sort, instead of offset.
> Maintain child order explicitly when building node views

- .yarn/versions/926015dc.yml
- src/components/__tests__/ProseMirror.node-view.test.tsx
- src/hooks/useEditor.ts
Fixes #28.
We were never setting `this.nodeViews` in the `ReactEditorView` constructor, so the latter `checkNodeViews` check was always failing, causing an infinite loop.
I added a whole test suite for custom node views so that we don't run into this kind of thing again without warning!
> Prevent infinite loop when node views passed as direct props

- .yarn/versions/22f7023f.yml
- package.json
- src/components/__tests__/ProseMirror.mobile.test.tsx
- src/plugins/beforeInputPlugin.ts
- wdio.conf.ts
This PR adds a fix for #70. 
This works by updating `src/plugins/beforeInputPlugin.ts` to handle `insertParagraph` and `insertLineBreak` event types and emits an "Enter" key event to any registered `keydown` handlers on the ProseMirror view. 
I've included wdio tests and split out mobile tests into their own suite, which makes it convenient to run via `npx wdio run ./wdio.conf.ts --suite mobile`.  Fortunately, it was pretty easy to add tests it turns out that wdio supports mobile emulation via: 
```
"goog:chromeOptions": {
mobileEmulation: {
deviceName: "Pixel 7",
},
},
```
> Fix Enter key not working on mobile Android devices running Chrome

- README.md
Hey there 👋
I was reading through the documentation and noticed that the yarn installation instructions listed `@handlewithcare/react-prosemirror` twice, so here's a tiny change for removing that extra item.
Thanks for the awesome library, cheers 🙌
> tidy: remove duplicate dependency from yarn installation instructions

- .yarn/versions/1bd89dbb.yml
- src/decorations/internalTypes.ts
- src/decorations/iterDeco.ts
- src/decorations/viewDecorations.tsx
Somehow we missed this bug fix to iterDecos from way back in 1.31.8: https://github.com/ProseMirror/prosemirror-view/commit/d48818c2f122c8c4b23b2b6bb9673462fc17af57. The result was that overlapping inline decorations that ended at the beginning of a block node could result in iterDecos emitting erroneous widget decorations, which then crashed the NativeWidgetView.
> Incorporate missed iterDeco fixes from prosemirror-view

- .yarn/versions/a7d451c4.yml
- src/components/ChildNodeViews.tsx
Addresses #63 
This was just a missing condition on our part. The result was that we sometimes added hack nodes to blocks that had blocks as children, which caused incorrect rendering behavior.
Also, I've decided that it's actually safe to use index-based keys for native widgets. They don't have any state, and we confirm that their dom matches their props on every render, so there's no risk of state mismatches if React swaps the props for a given NativeWidgetView component, if the order changes. As such, I've limited the warning about giving a key to widgets to react widgets.
> Only add text hack nodes to textblocks

- .yarn/versions/080ab2a3.yml
- src/plugins/beforeInputPlugin.ts
Well, this is a crazy one.
On macOS, in Safari, the OS will sometimes use compositions to suggest autocompletions. But for some reason, they do this by _only_ dispatching a compositionend event, with no associated compositionstart or compositionupdate. To be clear, the compositionend is dispatched when the suggestion is shown, not when the user selects it - I don't know why an event needs to be dispatched here at all, and certainly not why it would be a compositionend without a start.
Anyway, we need to handle the case where compositionend happens before compositionstart, apparently!
> Handle compositionend potentially being dispatched before compositionstart

- .yarn/versions/c7412ae7.yml
- package.json
- yarn.lock
Thank you for sharing this great library!
This is a pretty minor change, but I think react-reconciler should be a peer dep? Let me know if I'm missing some reason why this isn't desirable.
Either way, really appreciate this project and thanks again.
> Add react-reconciler as peer dependency

- .yarn/versions/f7b1387d.yml
- src/components/ChildNodeViews.tsx
- src/components/CustomNodeView.tsx
- src/components/DocNodeView.tsx
- src/components/MarkView.tsx
- src/components/NativeWidgetView.tsx
- src/components/NodeView.tsx
- src/components/ReactNodeView.tsx
- src/components/SeparatorHackView.tsx
- src/components/TextNodeView.tsx
- src/components/TrailingHackView.tsx
- src/components/WidgetView.tsx
- src/hooks/useNodeViewDescriptor.ts
Rather than passing refs to position functions, construct stable functions as callbacks that close over offset refs.
> refactor: use offset refs for position functions

- .yarn/versions/7fb36f6b.yml
- src/components/DocNodeView.tsx
- src/hooks/useNodeViewDescriptor.ts
This is a bit of a workaround for the fact that our contentDOM detection is imperfect. Specifically, we will not find a contentDOM for a non-textblock that _can_ have children but does not currently. This isn't a very common situation, but it does happen if you have a schema that allows a doc with no children and have an empty doc. So to work around the most common version of this, we always set contentDOM to the dom, since that is guaranteed to be the case for the doc node view
Fixes #110
> Always set the doc node view's contentDOM to its dom

- .yarn/versions/189b2a61.yml
- src/components/CustomNodeView.tsx
When custom node view constructors fail to return a valid node view, render the default node view for the node.
> fix: render fallbacks for custom node views

- .yarn/versions/033cc3e1.yml
- src/components/ChildNodeViews.tsx
Restore the correct order of hack nodes after they got reordered in the changes from #108.
Fix #131.
> fix: place image hack node before break hack node

- .yarn/versions/20a10cdf.yml
- src/ReactEditorView.ts
With #127, the node view descriptions get created only once the React editor view exists and the effects in `useNodeViewDescriptor` register the document view on the editor.
> refactor: remove misleading assignment of the editor document view

- .yarn/versions/ffb10f9c.yml
- src/ReactEditorView.ts
Override `ReactEditorView#destroy()` to prevent the editor from removing all of its React-managed children.
> fix: prevent the editor from destroying its content
